// Code generated by "makestatic"; DO NOT EDIT.

package static

var Files = map[string]string{
	"sidebar.html": "{{-\x20define\x20\"item\"\x20-}}\x0a{{-\x20range\x20.\x20}}\x0a\x20\x20<li>\x0a\x20\x20\x20\x20<a>{{.ImportPath}}</a>\x0a\x0a\x20\x20\x20\x20{{-\x20if\x20gt\x20(len\x20.SubPackages)\x200\x20}}\x0a\x20\x20\x20\x20<ul>{{template\x20\"item\"\x20.SubPackages}}</ul>\x0a\x20\x20\x20\x20{{-\x20end}}\x0a\x0a\x20\x20</li>\x0a{{-\x20end\x20-}}\x0a{{-\x20end\x20-}}\x0a\x0a<h3>Packages</h3>\x0a<div\x20class=\"col-md-3\x20col-xl-2\x20sidebar\">\x0a\x20\x20<ul>\x0a\x20\x20\x20\x20{{template\x20\"item\"\x20.tree}}\x0a\x20\x20</ul>\x0a</div>\x0a",

	"package.html": "{{template\x20\"sidebar.html\"}}\x0a\x0a<h1>\x0a\x20\x20Package\x20{{\x20.pkg.Name\x20}}\x0a</h1>\x0a\x0a<p>\x0a\x20\x20import\x20\"{{\x20.pkg.ImportPath\x20}}\"\x0a</p>\x0a\x0a<h2>Overview</h2>\x0a<div>{{\x20.pkg.Doc\x20}}</div>\x0a<div>{{\x20.pkg.ImportComment\x20}}</div>\x0a\x0a<h2>Imports</h2>\x0a<div>{{\x20.pkg.Imports\x20}}</div>\x0a\x0a<h2>Filenames</h2>\x0a<div>{{\x20.pkg.Filenames\x20}}</div>\x0a\x0a<h2>Notes</h2>\x0a<div>{{\x20.pkg.Notes\x20}}</div>\x0a\x0a<h2>Consts</h2>\x0a<div>{{\x20.pkg.Consts\x20}}</div>\x0a\x0a<h2>Types</h2>\x0a<div>{{\x20.pkg.Types\x20}}</div>\x0a\x0a<h2>Vars</h2>\x0a<div>{{\x20.pkg.Vars\x20}}</div>\x0a\x0a<h2>Funcs</h2>\x0a<div>{{\x20.pkg.Funcs\x20}}</div>\x0a\x0a<h2>Examples</h2>\x0a<div>{{\x20.pkg.Examples\x20}}</div>\x0a",
}
